### ISSUE TITLE
Great job, I'm looking forward to using it. ;) - Failed to activate the touchbar package

### ISSUE THREAD

**Issue by rubenalcala** [felixerdy/touchbar#1] opened 2017-06-23 19:29 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [touchbar](https://github.com/felixerdy/touchbar) package 0.3.4

### Stack Trace

Failed to activate the touchbar package

```
At Cannot read property 'items' of undefined

TypeError: Cannot read property 'items' of undefined
    at TimecopView.populateViews (/packages/touchbar/lib/touchbar-edit-view.js:45:79)
    at /packages/touchbar/lib/touchbar-edit-view.js:17:12)
    at Object.activate (/packages/touchbar/lib/touchbar.js:63:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:968:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:246:26)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (/Applications/Atom Beta.app/Contents/Resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:24.2.0 project-manager:list-projects (input.hidden-input)
     -0:22.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:16.3.0 project-manager:list-projects (input.hidden-input)
     -0:15 core:confirm (input.hidden-input)
     -0:14.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:08.9.0 docblockr:parse-enter (input.hidden-input)
     -0:08.9.0 editor:newline (input.hidden-input)
     -0:07.3.0 core:undo (input.hidden-input)
     -0:02.4.0 touchbar:toggle (input.hidden-input)
     -0:02.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
angularjs 0.4.0 
atom-beautify 0.30.3 
atom-browser 0.48.0 
atom-typescript 11.0.3 
autoclose-html 0.23.0 
busy-signal 1.4.3 
docblockr 0.10.5 
file-icons 2.1.7 
git-blame 1.1.1 
intentions 1.1.2 
language-blade 0.31.0 
laravel 0.7.1 
laravel-forms-bootstrap-snippets 1.2.0 
linter 2.2.0 
linter-jshint 3.1.2 
linter-php 1.3.2 
linter-ui-default 1.6.2 
merge-conflicts 1.4.5 
one-dark-vivid-syntax 1.7.1 
php-debug 0.2.4 
pretty-dir 0.0.17 
project-manager 3.3.5 
touchbar 0.3.4 
tree-view-autoresize 2.1.0 
```

**Comment by felixerdy** [comment] 2017-06-23 21:07
@rubenalcala thanks for your feedback! Could you maybe test it now again? I was not able to reproduce the error. It should be fixed now

**Comment by rubenalcala** [comment] 2017-06-24 11:24
@felixerdy works fine, thanks

**Closed** 2017-06-24 11:39 UTC
